[build-system]
# AVOID CHANGING REQUIRES: IT WILL BE UPDATED BY PYSCAFFOLD!
requires = ["setuptools>=46.1.0", "setuptools_scm[toml]>=5"]
build-backend = "setuptools.build_meta"

dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "tagging.__version__"}

#[tool.setuptools_scm]
# For smarter version schemes and other configuration options,
# check out https://github.com/pypa/setuptools_scm
#version_scheme = "no-guess-dev"


[semantic_release]
version_variable = "tagging/__init__.py:__version__"
branch = "master"
upload_to_pypi = false
build_command = "python -m build"
