name: Build and Release

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build python-semantic-release setuptools setuptools_scm wheel
    - name: Build package
      run: python -m build
      
    # Get version for master branch
    - name: Get Next Version
      if: github.ref == 'refs/heads/master'
      id: version
      run: |
        # Get the version that would be released
        VERSION=$(semantic-release version --print)
        echo "Next version will be: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    # For develop branch, use commit SHA
    - name: Get Develop Version
      if: github.ref == 'refs/heads/develop'
      id: dev_version
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "version=dev-$SHORT_SHA" >> $GITHUB_OUTPUT

    # Upload artifacts with version in name
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.ref == 'refs/heads/master' && format('package-v{0}', steps.version.outputs.version) || format('package-{0}', steps.dev_version.outputs.version) }}
        path: dist/*
    




    # Only run semantic release on master branch
    - name: Semantic Release
      if: github.ref == 'refs/heads/master'
      env:
        GH_TOKEN: ${{ secrets.GIT_PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        semantic-release publish
